[package]
name = "otter"
version = "0.0.1"
description = "The core library of otter"
homepage = "https://github.com/mogeko/otter/tree/master/crates/core"
repository = "https://github.com/mogeko/otter/tree/master/crates/core"
readme = "README.md"

[dependencies]
